background = "#111c18"
foreground = "#C1C497"
palette = [
  "#23372B",
  "#FF5345",
  "#549e6a",
  "#459451",
  "#509475",
  "#D2689C",
  "#2DD5B7",
  "#F6F5DD",
  "#53685B",
  "#db9f9c",
  "#63b07a",
  "#E5C736",
  "#ACD4CF",
  "#75bbb3",
  "#8CD3CB",
  "#9eebb3"
]
