background = "0x282828"
foreground = "0xd4be98"
palette = [
  "0x3c3836",
  "0xea6962",
  "0xa9b665",
  "0xd8a657",
  "0x7daea3",
  "0xd3869b",
  "0x89b482",
  "0xd4be98",
  "0x3c3836",
  "0xea6962",
  "0xa9b665",
  "0xd8a657",
  "0x7daea3",
  "0xd3869b",
  "0x89b482",
  "0xd4be98"
]
