background = "#2c2525"
foreground = "#e6d9db"
palette = [
  "#2c2525",
  "#fd6883",
  "#adda78",
  "#f9cc6c",
  "#f38d70",
  "#a8a9eb",
  "#85dacc",
  "#e6d9db",
  "#463a3a",
  "#ff8297",
  "#c8e292",
  "#fcd675",
  "#f8a788",
  "#bebffd",
  "#9bf1e1",
  "#f1e5e7"
]
