background = "#faf4ed"
foreground = "#575279"
palette = [
  "#f2e9e1",
  "#b4637a",
  "#286983",
  "#ea9d34",
  "#56949f",
  "#907aa9",
  "#d7827e",
  "#575279",
  "#9893a5",
  "#b4637a",
  "#286983",
  "#ea9d34",
  "#56949f",
  "#907aa9",
  "#d7827e",
  "#575279"
]
