background = "#121212"
foreground = "#bebebe"
palette = [
  "#333333",
  "#D35F5F",
  "#FFC107",
  "#b91c1c",
  "#e68e0d",
  "#D35F5F",
  "#bebebe",
  "#bebebe",
  "#8a8a8d",
  "#B91C1C",
  "#FFC107",
  "#b90a0a",
  "#f59e0b",
  "#B91C1C",
  "#eaeaea",
  "#ffffff"
]
